# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stock-api"
version = "0.1.0"
description = "Simple Stock Market API"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
]